"""use_cases_user_stories

Revision ID: 281cb1c25758
Revises: 67719f62d9de
Create Date: 2026-09-15 13:44:29.172080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '281cb1c25758'
down_revision: Union[str, Sequence[str], None] = '67719f62d9de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('use_cases',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('actors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preconditions', sa.Text(), nullable=True),
    sa.Column('postconditions', sa.Text(), nullable=True),
    sa.Column('main_flow', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alternative_flows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_use_case_code')
    )
    op.create_index(op.f('ix_use_cases_project_id'), 'use_cases', ['project_id'], unique=False)
    op.create_table('user_stories',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('benefit', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_user_story_code')
    )
    op.create_index(op.f('ix_user_stories_project_id'), 'user_stories', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stories_project_id'), table_name='user_stories')
    op.drop_table('user_stories')
    op.drop_index(op.f('ix_use_cases_project_id'), table_name='use_cases')
    op.drop_table('use_cases')
    # ### end Alembic commands ###
