"""traceability

Revision ID: 2df7d739f004
Revises: 281cb1c25758
Create Date: 2026-09-15 23:28:28.159870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df7d739f004'
down_revision: Union[str, Sequence[str], None] = '281cb1c25758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trace_links',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('from_type', sa.Enum('BUSINESS_GOAL', 'REQUIREMENT', 'USE_CASE', 'USER_STORY', name='traceentitytype'), nullable=False),
    sa.Column('from_id', sa.UUID(), nullable=False),
    sa.Column('to_type', sa.Enum('BUSINESS_GOAL', 'REQUIREMENT', 'USE_CASE', 'USER_STORY', name='traceentitytype'), nullable=False),
    sa.Column('to_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.Enum('DERIVES_FROM', 'SATISFIES', 'CONFLICTS_WITH', name='tracerelation'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'from_type', 'from_id', 'to_type', 'to_id', 'relation', name='uq_trace_link')
    )
    op.create_index(op.f('ix_trace_links_project_id'), 'trace_links', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_links_project_id'), table_name='trace_links')
    op.drop_table('trace_links')
    # ### end Alembic commands ###
