"""diagrams

Revision ID: efdebb72057b
Revises: 2df7d739f004
Create Date: 2026-09-17 13:29:54.200907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdebb72057b'
down_revision: Union[str, Sequence[str], None] = '2df7d739f004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagrams',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('USE_CASE', 'ER', 'CLASS', 'ACTIVITY', 'SEQUENCE', 'STATE', name='diagramtype'), nullable=False),
    sa.Column('mermaid_source', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_diagram_code')
    )
    op.create_index(op.f('ix_diagrams_project_id'), 'diagrams', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagrams_project_id'), table_name='diagrams')
    op.drop_table('diagrams')
    # ### end Alembic commands ###
